# Generated by Django 3.2.6 on 2021-08-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorations',
            name='category',
        ),
        migrations.AddField(
            model_name='decorations',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category'),
        ),
        migrations.RemoveField(
            model_name='decorations',
            name='material',
        ),
        migrations.AddField(
            model_name='decorations',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.material'),
        ),
    ]
