# Generated by Django 3.2.6 on 2021-08-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210816_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorations',
            name='description',
            field=models.CharField(default=0, help_text='Описание', max_length=1500),
            preserve_default=False,
        ),
    ]
