# Generated by Django 3.2.6 on 2021-08-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_decorations_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorations',
            name='description',
            field=models.CharField(help_text='Описание', max_length=1500, null=True),
        ),
    ]
