# Generated by Django 3.2.6 on 2021-08-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_decorations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorations',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decorations',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Категория изделия', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(help_text='Материал изделия', max_length=30, unique=True),
        ),
    ]
