# Generated by Django 3.2.6 on 2021-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210817_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Категория изделия', max_length=30, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(help_text='Материал изделия', max_length=30, unique=True, verbose_name='Метериал'),
        ),
    ]
