# Generated by Django 3.2.6 on 2021-08-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210817_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Категория изделия', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='decorations',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='decorations',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.material', verbose_name='Метериал'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(help_text='Материал изделия', max_length=30, unique=True),
        ),
    ]
