# Generated by Django 3.2.6 on 2021-08-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210817_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorations',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='decorations',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='decorations',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='decorations',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название изделия'),
        ),
        migrations.AlterField(
            model_name='decorations',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True, verbose_name='Цена'),
        ),
    ]
