# Generated by Django 3.2.6 on 2021-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210817_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=30, unique=True, verbose_name='Категория изделия'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(max_length=30, unique=True, verbose_name='Материал изделия'),
        ),
    ]
