# Generated by Django 3.2.6 on 2021-08-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210817_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gems', models.CharField(max_length=30, unique=True, verbose_name='Материал изделия')),
            ],
            options={
                'verbose_name': 'Драгоценный камень',
                'verbose_name_plural': 'Драгоценные камни',
            },
        ),
        migrations.AddField(
            model_name='decorations',
            name='gems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.gems', verbose_name='Драгоценные камни'),
        ),
    ]
