# Generated by Django 3.2.6 on 2021-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210817_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorations',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gems',
            name='gems',
            field=models.CharField(max_length=30, unique=True, verbose_name='Драгоценный камень'),
        ),
    ]
