# Generated by Django 3.2.6 on 2021-08-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_decorations_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorations',
            name='image',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('decorations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.decorations')),
            ],
        ),
    ]
