# Generated by Django 3.2.6 on 2021-08-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210818_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='decorations',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='images',
            name='decorations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.decorations', verbose_name='Название изделия'),
        ),
    ]
