# Generated by Django 3.2.6 on 2021-08-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210818_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorations',
            name='material',
        ),
        migrations.AddField(
            model_name='decorations',
            name='material',
            field=models.ManyToManyField(to='shop.Material', verbose_name='Материал'),
        ),
    ]
