# Generated by Django 3.2.6 on 2021-08-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20210818_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorations',
            name='gems',
        ),
        migrations.AddField(
            model_name='decorations',
            name='gems',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Gems', verbose_name='Драгоценные камни'),
        ),
        migrations.AlterField(
            model_name='decorations',
            name='material',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Material', verbose_name='Материал'),
        ),
    ]
