# Generated by Django 3.2.6 on 2021-08-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210818_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='decorations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.decorations', verbose_name='Название изделия'),
        ),
    ]
