# Generated by Django 3.2.6 on 2021-08-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_images_decorations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorations',
            name='gems',
            field=models.ManyToManyField(blank=True, to='shop.Gems', verbose_name='Драгоценные камни'),
        ),
        migrations.AlterField(
            model_name='decorations',
            name='material',
            field=models.ManyToManyField(blank=True, to='shop.Material', verbose_name='Материал'),
        ),
    ]
